module.exports = {
  ingorePaths: [
    'npm-shrinkwrap.json',
    'eweb/**',
    '**/dist/**',
    'dist/**',
    '**/node_module/**',
    'node_module/**',
    '**/*.jpg', '**/*.jpeg', '**/*.png', '**/*.svg', '**/*.eot', '**/*.ttf', '**/*.woff', '**/*.woff2', '**/*.gif',
    '*.jpg', '*.jpeg', '*.png', '*.svg', '*.eot', '*.ttf', '*.woff', '*.woff2', '*.gif',
  ],
  maxLineThreshold: 1500,
  svnProjectPaths: [
    { cwd: 'G:/SvnWorkspaces/eweb-11.0PS125', alias: '11.0PS125' },
    { cwd: 'G:/SvnWorkspaces/eweb-11.4PJ108', alias: '11.4PJ108' },
    { cwd: 'G:/SvnWorkspaces/eweb-11.4PJ109', alias: '11.4PJ109' },
    { cwd: 'G:/SvnWorkspaces/eweb-11.4PJ111', alias: '11.4PJ111' },
    { cwd: 'G:/SvnWorkspaces/eweb-11.4PS52', alias: '11.4PS52' },
    { cwd: 'G:/SvnWorkspaces/eweb-11.4PT138', alias: '' },
    { cwd: 'G:/SvnWorkspaces/eweb-12.4SPS8', alias: '' },
    { cwd: 'G:/SvnWorkspaces/eweb-11.0PS125', alias: '' },
    { cwd: 'G:/SvnWorkspaces/eweb-12.5SPJ20', alias: '' },
    { cwd: 'G:/SvnWorkspaces/eweb-12.5SPJ24', alias: '' },
    { cwd: 'G:/SvnWorkspaces/eweb-12.5SPJ25-1', alias: '' },
    { cwd: 'G:/SvnWorkspaces/eweb-12.5SPJ25-2', alias: '' },
    { cwd: 'G:/SvnWorkspaces/eweb-12.5SPJ13', alias: '' },
    { cwd: 'G:/SvnWorkspaces/eweb-12.5SPS10', alias: '' },
    { cwd: 'G:/SvnWorkspaces/20220620-emb-1.19.0-12.6SPJ2', alias: '' },
    { cwd: 'G:/SvnWorkspaces/20220518-mf-eweb-cmps-ms', alias: 'mf' },
    { cwd: 'D:/SvnWorkspaces/us_eweb/us-eweb/trunk/code/eweb-ui', alias: 'cmps-inc-emb-trunk' },
    { cwd: 'G:/SvnWorkspaces/20220629-inc-inc-emb-trunk-yr', alias: 'emb-trunk-yr' },
  ],
  debug: true,
  svnStartDayTime: "2021-01-01 00:00:00",
  svnEndDayTime: "2022-01-01 00:00:00",
  outDir: '.'
}
